### PR TITLE
add basic text functions

### PR DESCRIPTION
**Pull request by dwarring**
I'm putting it to work in some modules that I'm building at the moment for building and rendering HTML Canvases https://github.com/p6-css/HTML-Canvas-p6 https://github.com/p6-css/HTML-Canvas-To-Cairo-p6

### CODE REVIEW

**Comment by dwarring** [comment]
@timo just looking for feedback.

Still more, functions I'd like to add, such as transform and set_matrix/get_matrix from https://cairographics.org/manual/cairo-Transformations.html

Also looking at cairo_image_surface_create_from_png () https://cairographics.org/manual/cairo-PNG-Support.html

**Comment by timo** [comment]
the code looks good. there's just two lines with strange indent in font_extents and text_extents

**Comment by dwarring** [comment]
@timo 
thanks for that, have added `(setq-default indent-tabs-mode nil)` to my `.emacs` to disable tabs.

**Comment by timo** [comment]
would you like to become a contributor on the repo for access to master (and, if you'd prefer, to have your branch in the "official" repo)?

**Comment by dwarring** [comment]
Hi Timo,
Happy to both have access and have the branch moved the official repo.
- David

**Comment by dwarring** [comment]
I took the examples from https://www.cairographics.org/samples/. They all ported pretty easily with just a few tweaks to this module :-)

Now mostly done with the changes on this branch.

**Comment by dwarring** [comment]
Replacing this PR with dwarring-text branch in this repo

**Pull request closed without merging**
